if [ -f ~/.aliases ]; then
    . ~/.aliases
fi

export NVM_DIR="/Users/glenn/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

# Add RVM to PATH for scripting
# export PATH="/usr/local/git/bin/git:$PATH:$HOME/.rvm/bin"
export PATH="/usr/local/git/bin/git:$PATH"
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
