if [ -f ~/.aliases ]; then
    . ~/.aliases
fi

export NVM_DIR="/Users/glenn/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
