# Move these to .extra or .local or down to a ruby section
export RUBYOPT=rubygems

# probably don't need these anymore
# export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
# export PATH="/usr/local/bin:/usr/local/sbin:/usr/local/mysql/bin:$PATH"

# This loads RVM into a shell session.
# export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
#[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"


# Add `~/bin` to the `$PATH`
export PATH="$HOME/bin:$PATH";


# Load the shell dotfiles, and then some:
# * ~/.path can be used to extend `$PATH`.
# * ~/.extra can be used for other settings you don’t want to commit.
for file in ~/.{path,bash_prompt,exports,aliases,functions,extra}; do
  [ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;


# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob;

# Append to the Bash history file, rather than overwriting it
shopt -s histappend;

# Autocorrect typos in path names when using `cd`
shopt -s cdspell;


# Enable some Bash 4 features when possible:
# * `autocd`, e.g. `**/qux` will enter `./foo/bar/baz/qux`
# * Recursive globbing, e.g. `echo **/*.txt`
for option in autocd globstar; do
  shopt -s "$option" 2> /dev/null;
done;


# Add tab completion for many Bash commands
if [ "$(uname)" == "Darwin" ]; then
  if which brew > /dev/null && [ -f "$(brew --prefix)/etc/bash_completion" ]; then
    source "$(brew --prefix)/etc/bash_completion";
  fi;
elif [ -f /etc/bash_completion ]; then
  source /etc/bash_completion;
fi;


# Add tab completion for SSH hostnames based on ~/.ssh/config, ignoring wildcards
[ -e "$HOME/.ssh/config" ] && complete -o "default" -o "nospace" -W "$(grep "^Host" ~/.ssh/config | grep -v "[?*]" | cut -d " " -f2- | tr ' ' '\n')" scp sftp ssh;

# Move these to .extra or .local
# ORIG FROM RHEL BOX
export NETREPO=svn+ssh://svn.corp.linkedin.com/netrepo/network
export LIREPO=svn+ssh://svn.corp.linkedin.com/lirepo
export VENREPO=svn+ssh://svn.corp.linkedin.com/vendor

export JAVA_HOME=/export/apps/jdk/JDK-1_8_0_40
export JDK_HOME=/export/apps/jdk/JDK-1_8_0_40

export NLS_LANG=American_America.UTF8

#export M2_HOME=/usr/local/apache-maven
#export M2=$M2_HOME/bin
# if using maven, prepend $M2: to PATH= below

export PATH=$PATH:$JAVA_HOME/bin:/usr/local/bin:/usr/local/mysql/bin:/usr/local/linkedin/bin:/export/content/linkedin/bin

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*


