#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
source ~/dotfiles/shell/aliases
source ~/dotfiles/shell/functions
source ~/.extra


# ZLE_RPROMPT_INDENT=0
# ZLE_PROMPT_INDENT=1

# Turn off command autocorrection
unsetopt CORRECT

# Load z
. /usr/local/etc/profile.d/z.sh

# Unalias g=git created by zprezto's git module
unalias g
# Unalias git force push
unalias gpf

# Add RVM to PATH for scripting
# export PATH="/usr/local/git/bin/git:$PATH:$HOME/.rvm/bin"
export PATH="/usr/local/git/bin/git:$PATH"
