"set gfn=Meslo\ LG\ L\ DZ\ Regular\ for\ Powerline\ Nerd\ Font\ Complete\ Mono:h10
set gfn=Sauce\ Code\ Pro\ Light\ Nerd\ Font\ Complete:h10
" linespace only works in gui vim, not terminal vim
set linespace=3
set guioptions=
