set nocompatible " D_Fisable legacy vi compatiblity

" Start vim-plug
" Some vim-plug cmds: PlugInstall, PlugUpdate, PlugClean, PlugUpgrade
call plug#begin('~/.vim/bundle')
 Plug 'mileszs/ack.vim' " Vim ack/ag integration
 Plug 'bling/vim-airline' " Fancy statusbar
 Plug 'vim-airline/vim-airline-themes' " Themes for fancy statusbar
 Plug 'jiangmiao/auto-pairs' " Automatically insert pairs of quotes/braces/brackets while typing
 Plug 'ntpeters/vim-better-whitespace' " Highlight trailing whitespace
 Plug 'jeetsukumaran/vim-buffergator' " Buffer management
 Plug 'docunext/closetag.vim' " Auto html5 tag closer
 Plug 'ctrlpvim/ctrlp.vim', " Fuzzy filename matcher
 Plug 'raimondi/delimitmate' " Insert-mode auto-completion for quotes, parens, brackets
 Plug 'junegunn/vim-easy-align' " Alignment
 Plug 'editorconfig/editorconfig-vim' " For consistent coding style
 Plug 'isruslan/vim-es6' " es6 syntax and snippets
 Plug 'mattn/emmet-vim' " Emmet expansion
 Plug 'tpope/vim-fugitive' " Git inigration for vim
 Plug 'ktonga/vim-follow-my-lead' " ,fml to display all leader key mappings
 Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
 Plug 'junegunn/fzf.vim' " Fuzzy finder vim plugin for fzf above
 Plug 'justinmk/vim-gtfo' " Go to terminal or file manager
 Plug 'airblade/vim-gitgutter' " Git in ur gutter
 Plug 'othree/html5.vim' " HTML5 syntax enhancements
 Plug 'nathanaelkane/vim-indent-guides' " Visually display indent guides
 Plug 'pangloss/vim-javascript' " Better es6/es2015 syntax support
 Plug 'Valloric/ListToggle' " Quickly toggle Quickfix and Location panels
 Plug 'elzr/vim-json' " JSON syntax enhancments for vim
 Plug 'lukhio/vim-mapping-conflicts' " :CheckMapping checks for key mapping conflicts
 Plug 'terryma/vim-multiple-cursors' " ST3 style multi selection
 Plug 'mustache/vim-mustache-handlebars' " Handlebars syntax enhancements
 Plug 'scrooloose/nerdtree' " File manager
 Plug 'scrooloose/nerdcommenter' " Quickly toggle comment blocks
 Plug 'tiagofumo/vim-nerdtree-syntax-highlight' " Colored nerdtree icons
 Plug 'xuyuanp/nerdtree-git-plugin' " Git status in nerdtree
 Plug 'cakebaker/scss-syntax.vim' " Sass/Scss syntax enhancements
 Plug 'slim-template/vim-slim' " Syntax highlighting
 Plug 'andrewradev/splitjoin.vim' " Split and join lines
 Plug 'mhinz/vim-startify' " Fancy start screen showing recently edited files
 Plug 'ervandew/supertab' " Tab autocompletion
 Plug 'tpope/vim-surround' " Plugin for working with quotes/braces/brackets etc
 Plug 'scrooloose/syntastic' " Linter

" Color Themes
 Plug 'jdkanani/vim-material-theme'

  " Dev icons. (must load last)
  Plug 'ryanoasis/vim-devicons' " Nerd fonts file/symbol icons
call plug#end()


" General defaults
filetype plugin indent on " Allow smart indentation and filetype detection
set encoding=utf8 nobomb " Set charset to utf8 (Necessary for fancy icon plugins)
syntax enable " Turn on syntax highlighting
set number " Turn on line numbers
set bg=dark " Dark background
set hidden " Allow 'hidden' buffers
set nowrap " Disable line auto wrapping
set cursorline " highlight current line
set numberwidth=5 " Gutter width
set autoread " Auto re-read files that have changes outside of vim
set lazyredraw
set mouse=a " Turn on the mouse ;)
set mousehide " hide the mouse in the gui while typing
set ttymouse=xterm2 " Support resizing
set ttyfast   " Optimize for fast terminal connections
set history=50
set scrolloff=3   " Start scrolling three lines before the horizontal window border
set nostartofline   " Don’t reset cursor to start of line when moving around.
set clipboard=unnamed   " yank and paste with the system clipboard


" Swap/Backup file settings
set noswapfile " no more weirdo swap files
set nobackup " no more weirdo backup files
set nowritebackup " no more weirdo write backup files
set backupdir=~/.backup " Where backups would go if we had them
set dir=~/.swap " Where swap files would go if we had them
set directory-=.   " don't store swapfiles in the current directory


" Split/window behavior
set splitright " Open vertical splits/windows to the right by default
set splitbelow " Open horizontal splits/windows to the bottom by default
set switchbuf=useopen " Switch to active window if attempting to split an already active buffer


" Search settings
set ignorecase " case-insensitive searching
set smartcase " make search case-sensitive if search term contains mixed case
set hlsearch " Highlight search pattern matches
set incsearch " Add live highlighting to matches while typing search term


" Indentation settings
let g:indentation_depth = 2
let &tabstop=g:indentation_depth " Set tab character width
let &backspace=g:indentation_depth " Make backspace work like a sane person would expect
let &shiftwidth=g:indentation_depth " Set distance to move lines or blocks
let &softtabstop=g:indentation_depth " Set space added by pressing tab key and removed by pressing backspace
set backspace=indent,eol,start   " Backspace through everything in INSERT mode
set autoindent " keeps indention at current depth for successive lines
set copyindent " copy the previous indentation on autoindenting
set expandtab " Convert tabs to spaces
let g:indent_guides_start_level=2
let g:indent_guides_guide_size=1


" Always use vertical diffs
set diffopt+=vertical


" Code folding & wrap guides
set foldcolumn=2
set foldlevel=99 " show all folds by default
set foldlevelstart=99 " show all folds by default
set fcs=fold:-
set textwidth=80 " text wrap
"set colorcolumn=+1 " Make it obvious where 80 characters is


" Startify settings
let g:startify_session_autoload = 1
let g:startify_session_persistence = 1
let g:startify_change_to_vcs_root = 1


" Filetype settings
if has("autocmd")
  " Languages with specific tabs/space requirements
  autocmd FileType make setlocal ts=4 sts=4 sw=4 noexpandtab
  " Automatically strip trailing whitespace on file save using better-whitespace
  autocmd FileType css,html,js,json,md,php,py,rb,scss,sh,txt autocmd BufEnter <buffer> EnableStripWhitespaceOnSave
  " Don't treat json as javascript
  autocmd BufRead,BufNewFile *.json set filetype=json
  " fdoc is yaml
  autocmd BufRead,BufNewFile *.fdoc set filetype=yaml
  " md is markdown
  autocmd BufRead,BufNewFile *.md set filetype=markdown
  autocmd BufRead,BufNewFile *.md set spell
  " automatically rebalance windows on vim resize
  autocmd VimResized * :wincmd =
endif


" GUI & Theme settings
if $TERM_PROGRAM =~ 'iTerm'
  " True color. Requires Vim v.7.4.1799 or greater
  set termguicolors
  colorscheme material-theme
else
  " 256 color terminal support
  set t_Co=256
  colorscheme sweater
endif


" Status & Info settings
if has("cmdline_info")
  " Show the cursor line and column number
  set ruler
  " Show partial commands in status line
  set showcmd
  " Show whether in insert or replace mode
  set showmode
endif
if has('statusline')
  " Always show status line
  set laststatus=2
  " Broken down into easily includeable segments
  " Filename
  set statusline=%<%f\
  " Options
  set statusline+=%w%h%m%r
  " Current dir
  set statusline+=\ [%{getcwd()}]
  " Right aligned file nav info
  set statusline+=%=%-14.(%l,%c%V%)\ %p%%
  " scrooloose/syntastic
  set statusline+=%#warningmsg#
  set statusline+=%{SyntasticStatuslineFlag()}@/T7
  set statusline+=%*
endif


" Wildmenu settings - for command autocompletion
if has("wildmenu")
  set wildmenu " Show completion options (filenames, plugin functions, etc) in a traversable menu
  " Tab autocomplete longest possible part of a string, then list
  set wildmode=longest,list,full
  if has ("wildignore")
    set wildignore+=*.a,*.pyc,*.o,*.orig
    set wildignore+=*.bmp,*.gif,*.ico,*.jpg,*.jpeg,*.png
    set wildignore+=.DS_Store,.git,.hg,.svn
    set wildignore+=*~,*.sw?,*.tmp
    set wildignore=log/**,node_modules/**,*/bower_components/*,target/**,tmp/**,*.rbc
  endif
endif


" Search plugin settings
if executable('ag')
  " Use Ag over Grep
  set grepprg=ag\ --vimgrep\ $*
  set grepformat=%f:%l:%c:%m

  " Use ag in CtrlP for listing files. Lightning fast and respects .gitignore
  let g:ctrlp_user_command = 'ag %s -l -g ""'

  " ag is fast enough that CtrlP doesn't need to cache
  let g:ctrlp_use_caching = 0
endif
if executable('ack')
  let g:ackprg = 'ag --vimgrep'
  let g:ackhighlight = 1
endif
if executable('rg')
  " If ripgrep exists use it instead of ag
  set grepprg=rg\ --vimgrep
endif

" FZF Settings
command! -bang -nargs=* Find call fzf#vim#grep('rg --column --line-number --no-heading --fixed-strings --ignore-case --hidden --glob "!.git/*" --color "always" '.shellescape(<q-args>), 1, <bang>0)

" CtrlP settings
set runtimepath^=~/.vim/bundle/ctrlp.vim
let g:ctrlp_show_hidden = 1 " Show hidden files when using ctrlp
let g:ctrlp_match_window = 'order:ttb,max:20'



" TMUX Settings
if exists('$TMUX')
  " Fix Cursor in TMUX
  let &t_SI = "\<ESC>Ptmux;\<ESC>\<ESC>]50;CursorShape=1\x7\<ESC>\\"
  let &t_EI = "\<ESC>Ptmux;\<ESC>\<ESC>]50;CursorShape=0\x7\<ESC>\\"
else
  let &t_SI = "\<ESC>]50;CursorShape=1\x7"
  let &t_SR = "\<ESC>]50;CursorShape=2\x7"
  let &t_EI = "\<ESC>]50;CursorShape=0\x7"
endif



" Gitgutter settings
let g:gitgutter_enabled = 1


" vmustache/vim-mustache-handlebars settings
let g:mustache_abbreviations = 1

" scrooloose/nerdtree setings
let NERDTreeHijackNetrw = 0 " For Startify session autoload
let g:NERDSpaceDelims=1
let NERDTreeMouseMode = 2
let NERDTreeRespectWildIgnore = 1
let NERDTreeMinimalUI = 1
let NERDTreeAutoDeleteBuffer = 1
let NERDTreeIgnore=[
      \'^pemberly$',
      \'^\.gradle$',
      \'^\.log$',
      \'^logs$',
      \'^i18n$',
      \'^node_modules$',
      \'^dist$',
      \'^tmp$',
      \'^bower_components$',
      \'^coverage$',
      \'^build$',
      \'^acl$',
      \'^screenshots$',
      \'^tools$',
      \'^vendor$',
      \'^docs$',
      \'^out$',
      \'^public$']


" tiagofumo/vim-nerdtree-syntax-highlight
let s:yellow = "F2DD58"
let s:green = "8FAA54"
let g:NERDTreeExtensionHighlightColor = {} " this line is needed to avoid error
let g:NERDTreeExtensionHighlightColor['js'] = s:yellow " make js a brighter yellow
let g:NERDTreeExactMatchHighlightColor = {} " this line is needed to avoid error
let g:NERDTreeExtensionHighlightColor['json'] = s:green " make json green
let g:NERDTreePatternMatchHighlightColor = {} " this line is needed to avoid  error

" scrooloose/syntastic settings
let g:syntastic_javascript_eslint_exec = '$PWD/node_modules/.bin/eslint'
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_loc_list_height = 5
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_javascript_checkers = ['eslint']
let g:syntastic_error_symbol = '✖'
let g:syntastic_style_error_symbol = '✖'
let g:syntastic_warning_symbol = '⚠'
let g:syntastic_style_warning_symbol = '⚠'

" ryanoasis/vim-devicons
let g:WebDevIconsUnicodeDecorateFolderNodes = 1


" airline settings
let g:airline_powerline_fonts = 1
if !exists('g:airline_symbols')
  let g:airline_symbols = {}
endif
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#fnamemod = ':t'
let g:airline_symbols.space = "\ua0"
let g:airline_theme='bubblegum'
let g:airline#extensions#branch#enabled = 1
let g:airline#extensions#branch#empty_message = ''
let g:airline#extensions#branch#displayed_head_limit = 10
let g:airline#extensions#syntastic#enabled = 1
let g:airline#extensions#bufferline#enabled = 0
let g:airline#extensions#whitespace#enabled = 1
let g:airline#extensions#whitespace#mixed_indent_algo = 1
let g:airline#extensions#whitespace#symbol = '!'
let g:airline#extensions#whitespace#checks = [ 'indent', 'trailing' ]
let g:airline#extensions#whitespace#trailing_format = 'trailing[%s]'
let g:airline#extensions#whitespace#mixed_indent_format = 'mixed-indent[%s]'


" elzr/vim-json
let g:vim_json_syntax_conceal = 0

" pangloss/vim-javascript
let g:javascript_plugin_jsdoc = 0

" heavenshell/vim-jsdoc
let g:jsdoc_enable_es6 = 1
let g:jsdoc_allow_input_prompt = 1

" follow my lead (fml) settings
let g:fml_all_sources = 1


" ===============================================
"                   KEYMAPS
" ===============================================
let mapleader = ","
" \/ turn off highlighting after a search
nmap <silent> <leader>/ :nohl<CR>
inoremap jj <ESC>



"---------- Editor Modification ----------
" Insert newline
map <leader><Enter> o<ESC>

" Search and replace word under cursor (,*)
nnoremap <leader>* :%s/\<<C-r><C-w>\>//<Left>

" Join lines and restore cursor location (J)
nnoremap J mjJ`j

" Make `Y` work from the cursor to the end of line (which is more logical)
nnoremap Y y$

" Make dd delete (not cut) entire line
nnoremap d "_d
vnoremap d "_d

" Indent/Unindent and keep highlighted
vnoremap > ><CR>gv
vnoremap < <<CR>gv

" Paste toggle ()
nnoremap <F2> :set invpaste paste?<CR>
set pastetoggle=<F2>
set showmode

" Move current line or selected block up/down. Works in normal, insert and visual modes
" For Mac only! Alt+j/k
nnoremap ∆ :m .+1<CR>
nnoremap ˚ :m .-2<CR>
inoremap ∆ <ESC>:m .+1<CR>
inoremap ˚ <ESC>:m .-2<CR>
vnoremap ∆ :m '>+1<CR>
vnoremap ˚ :m '<-2<CR>

" Custom keymap for vim-multiple-cursors
let g:multi_cursor_use_default_mapping=0
let g:multi_cursor_next_key='<C-d>'
let g:multi_cursor_prev_key='<C-p>'
let g:multi_cursor_skip_key='<C-x>'
let g:multi_cursor_quit_key='<ESC>'

" Sudo write (,W)
noremap <leader>W :w !sudo tee %<CR>
nnoremap <leader>w :w!<CR>
nnoremap <leader>wq :wq!<CR>
nnoremap <leader>wa :wa!<CR>
noremap <leader>qa :qa!<CR>


"---------- Editor Movement/Navigation ----------
" Better mark jumping (line + col)
nnoremap ' `

" Toggle folds (<Space>)
nnoremap <silent> <space> :exe 'silent! normal! '.((foldclosed('.')>0)? 'zMzx' : 'zc')<CR>



"---------- File Navigation ----------
" Next/prev buffer
nnoremap <Tab> :bnext<CR>
nnoremap <S-Tab> :bprev<CR>
" Delete (close) buffer
map <leader>d :bp\|bd #<CR>
" Vim list buffers
map <leader>ls :buffers<CR>

" File Tabs
nnoremap <leader>th :tabprev<CR>
nnoremap <leader>tl :tabnext<CR>
nnoremap <leader>tn :tabnew<CR>
nnoremap <leader>tw :tabclose<CR>

" Window navigation
noremap <C-h> <C-w>h
noremap <C-j> <C-w>j
noremap <C-k> <C-w>k
noremap <C-l> <C-w>l




"---------- Resizing ----------
" Resizing a window split Maps Alt-[h,l]
map <silent> ˙ <C-w>>
map <silent> ¬ <C-w><
" Maps Alt-[s,v] to horizontal and vertical split respectively
map <silent> ß :split<CR>
map <silent> √ :vsplit<CR>



"---------- Plugin-related Keymaps ----------
nnoremap <leader>gs :Gstatus<CR><C-w>t<C-w>H
nnoremap <leader>gb :Gblame<CR>
noremap <leader>g :GitGutterToggle<CR>
noremap <leader>i :IndentGuidesToggle<CR>
" Custom FZF find
nnoremap <C-f> :Find<space>
imap <C-x><C-l> <plug>(fzf-complete-line)
nnoremap <leader>a :Ack!<space>
nnoremap <leader>aq :Ack! -Q<space>
nnoremap <leader>nt :NERDTreeToggle<CR>
nnoremap <leader>nf :NERDTreeFind<CR>
nnoremap <leader>b :CtrlPBuffer<CR>
nnoremap <leader>P :CtrlPClearCache<CR>:CtrlP<CR>
nnoremap <leader>S :Startify<CR>

" Hot Reload vimrc
noremap <silent> <leader>V :source ~/.vimrc<CR>:filetype detect<CR>:exe ":echo 'vimrc reloaded'"<CR>

" Start interactive EasyAlign for a motion/text object (e.g. gaip)
nmap ga <Plug>(EasyAlign)

" Valloric/ListToggle
let g:lt_location_list_toggle_map = '<leader>l'
let g:lt_quickfix_list_toggle_map = '<leader>q'






" Load local machine settings if they exist
if filereadable(glob("$HOME/.vimrc.local"))
  "set shell=zsh " Local shell. Set in .vimrc.local.
  source $HOME/.vimrc.local
endif
